###################################################################################################
#
# Primordial Machine's Relational Functors Library
# Copyright (C) 2017-2019 Michael Heilmann
#
# This software is provided 'as-is', without any express or implied warranty.
# In no event will the authors be held liable for any damages arising from the
# use of this software.
#
# Permission is granted to anyone to use this software for any purpose,
# including commercial applications, and to alter it and redistribute it
# freely, subject to the following restrictions:
#
# 1. The origin of this software must not be misrepresented;
#    you must not claim that you wrote the original software.
#    If you use this software in a product, an acknowledgment
#    in the product documentation would be appreciated but is not required.
#
# 2. Altered source versions must be plainly marked as such,
#    and must not be misrepresented as being the original software.
#
# 3. This notice may not be removed or altered from any source distribution.
#
###################################################################################################

# ORGANIZATION_NAME
#   The name of the publishing organization.
#   Example: 'primordialmachine'.
# PACKAGE_NAME
#   The name of the published package.
#   Example: 'one-zero-functors'.
# CONFIGURATION:
#   The configuration.
#   Example: 'release'.
# PLATFORM:
#   The platform.
#   Example: 'x64'.
# ARTIFACT_FILENAME
#   The file name of the artifact.
#   Example: 'primordialmachine-one-zero-functors-release-x64.zip'.
# ARTIFACT_NAME
#   The name of the artifact.
#   Example: 'primordialmachine-one-zero-functors-release-x64'.
#
# GOOGLETESTADAPTER_FILENAME
#   The filename of the archive of GoogleTestAdapter.
#   Example: 'GoogleTestAdapter-0.14.0.vsix'.
# GOOGLETESTADAPTER_URL
#   The URL of the archive of GoogleTestAdapter.
#   Example: 'https://github.com/csoltenborn/GoogleTestAdapter/releases/download/v0.14.0/GoogleTestAdapter-0.14.0.vsix'.
# MIKTEX_FILENAME
#   The filename of the archive of MikTex.
#   Example: 'miktex-portable-2.9.6753.exe'.
# MIKTEX_URL
#   The URL of the archive of MikTex.
#   Example: 'https://miktex.org/download/ctan/systems/win32/miktex/setup/windows-x86/miktex-portable-2.9.6753.exe'.

clone_depth: 1

image: Visual Studio 2017 # Build worker image (VM template)

branches:
  only:
    - develop

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

environment:
  # Environment variables pertaining to the organization and package.
  ORGANIZATION_NAME : "primordialmachine"
  PACKAGE_NAME : "one-zero-functors"
  # Environment variables pertaining to GoogleTestAdapter.
  GOOGLETESTADAPTER_FILENAME : "GoogleTestAdapter-0.14.0.vsix"
  GOOGLETESTADAPTER_URL : "https://github.com/csoltenborn/GoogleTestAdapter/releases/download/v0.14.0/GoogleTestAdapter-0.14.0.vsix"
  GOOGLETESTADAPTER_INSTALL_PATH : "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\IDE\\GoogleTestAdapter-0.14.0"
  # Environment variables pertaining to MikTex.
  MIKTEX_FILENAME : "miktex-portable-2.9.6942.exe"
  MIKTEX_URL : "https://miktex.org/download/ctan/systems/win32/miktex/setup/windows-x86/miktex-portable-2.9.6942.exe"
  MIKTEX_INSTALL_PATH : "C:\\miktex"

cache:
  # Cache archive and installation of GoogleTestAdapter.
  - "%GOOGLETESTADAPTER_FILENAME% -> appveyor-develop.yml"
  - "%GOOGLETESTADAPTER_INSTALL_PATH% -> appveyor-develop.yml"
  # Cache archive and installation of MikTex.
  - "%MIKTEX_FILENAME% -> appveyor-develop.yml"
  - "%MIKTEX_INSTALL_PATH% -> appveyor-develop.yml"

install:
  # Download and install GoogleTestAdapter.
  # Use cached archives/installations if possible.
  - IF NOT EXIST "%GOOGLETESTADAPTER_FILENAME%" (appveyor DownloadFile "%GOOGLETESTADAPTER_URL%" -FileName "%GOOGLETESTADAPTER_FILENAME%")
  - IF EXIST "%GOOGLETESTADAPTER_INSTALL_PATH%" (ECHO "using cached GoogleTestAdapter")
  - IF NOT EXIST "%GOOGLETESTADAPTER_INSTALL_PATH%" (7z x "%GOOGLETESTADAPTER_FILENAME%" -o"%GOOGLETESTADAPTER_INSTALL_PATH%" > nul)
  # Download and install MikTex.
  # Use cached archives/installations if possible.
  - IF NOT EXIST "%MIKTEX_FILENAME%" (appveyor DownloadFile "%MIKTEX_URL%" -FileName "%MIKTEX_FILENAME%")
  - IF EXIST "%MIKTEX_INSTALL_PATH%" (ECHO "using cached MikTex")
  - IF NOT EXIST "%MIKTEX_INSTALL_PATH%" (7z x "%MIKTEX_FILENAME%" -o"%MIKTEX_INSTALL_PATH%" > nul)
  - set "PATH=%PATH%;%MIKTEX_INSTALL_PATH%\texmfs\install\miktex\bin"
  - initexmf --set-config-value "[MPM]AutoInstall=1"

before_build:
  - nuget restore         # Restore NuGet packages.
  - ps: |
      $env:ARTIFACT_NAME="$($env:ORGANIZATION_NAME.tolower())-$($env:PACKAGE_NAME.tolower())-$($env:configuration.tolower())-$($env:platform.tolower())"
      $env:ARTIFACT_FILENAME="$($env:ARTIFACT_NAME).zip"
      $env:DOCUMENTATION_ARTIFACT_NAME="$($env:ORGANIZATION_NAME.tolower())-$($env:PACKAGE_NAME.tolower())-$($env:configuration.tolower())-$($env:platform.tolower())"
      $env:DOCUMENTATION_ARTIFACT_FILENAME="$($env:DOCUMENTATION_ARTIFACT_NAME).pdf"

build_script:
  - ps: |
      msbuild solution.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: |
      cd documentation
      latexmk -pdf index.tex
      cd ..

after_build:
   - ps: |
       cd packages
       7z a $env:ARTIFACT_FILENAME $($env:ORGANIZATION_NAME.tolower())
       Move-Item -Path ./$env:ARTIFACT_FILENAME -Destination ./../$env:ARTIFACT_FILENAME
       cd ..
   - ps: |
       Move-Item -Path documentation/index.pdf -Destination ./$env:DOCUMENTATION_ARTIFACT_FILENAME

test_script:
  - ps: |
      $logger="Appveyor"
      $configuration=$env:configuration
      $platform=$env:platform
      $testAdapterPath="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\GoogleTestAdapter-0.14.0"
      $testPath="products\test\$platform\$configuration\$($env:PACKAGE_NAME.tolower())-test.exe"
      vstest.console /Logger:$logger /Platform:$platform /TestAdapterPath:$testAdapterPath /inIsolation $testPath

artifacts:
  - path: $(ARTIFACT_FILENAME)
    name: $(ARTIFACT_NAME)
  - path: $(DOCUMENTATION_ARTIFACT_FILENAME)
    name: $(DOCUMENTATION_ARTIFACT_NAME)

matrix:
  fast_finish: true       # If one matrix entry fails, all entries fails.

notifications:
